### ISSUE TITLE
Install & Upgrade error on XF 2.1

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2-installupgrade#10]
After adding TH API credentials I see the below:

ErrorException: Template error: Cannot call method count on a non-object (array) src/XF/Template/Templater.php:963
Generated by: nik Feb 7, 2019 at 4:08 PM
Stack trace
#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Cannot call met...', '/home/nginx/dom...', 963, Array)
#1 src/XF/Template/Templater.php(963): trigger_error('Cannot call met...', 512)
#2 internal_data/code_cache/templates/l1/s0/admin/th_iau_addon_install_upgrade.php(118): XF\Template\Templater->method(Array, 'count', Array)
#3 src/XF/Template/Templater.php(1294): XF\Template\Templater->{closure}(Object(XF\Template\Templater), Array)
#4 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('th_iau_addon_in...', Array)
#5 src/XF/Mvc/Renderer/Json.php(84): XF\Template\Template->render()
#6 src/XF/Mvc/Renderer/Json.php(68): XF\Mvc\Renderer\Json->renderHtmlFallback('ThemeHouse\\Inst...', 'admin:th_iau_ad...', Array)
#7 src/XF/Mvc/Dispatcher.php(418): XF\Mvc\Renderer\Json->renderView('ThemeHouse\\Inst...', 'admin:th_iau_ad...', Array)
#8 src/XF/Mvc/Dispatcher.php(400): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Json), Object(XF\Mvc\Reply\View))
#9 src/XF/Mvc/Dispatcher.php(360): XF\Mvc\Dispatcher->renderReply(Object(XF\Mvc\Renderer\Json), Object(XF\Mvc\Reply\View))
#10 src/XF/Mvc/Dispatcher.php(53): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'json')
#11 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#12 src/XF.php(390): XF\App->run()
#13 admin.php(13): XF::runApp('XF\\Admin\\App')
#14 {main}
Request state
array(4) {
  ["url"] => string(189) "/community/admin.php?add-ons/th-install-upgrade&_xfRequestUri=%2Fcommunity%2Fadmin.php%3Fadd-ons%2F&_xfWithData=1&_xfToken=1549555710%2C672df1439f82b3c90602c46bd5c9c314&_xfResponseType=json"
  ["referrer"] => string(50) "https://mysite.com/community/admin.php?add-ons/"
  ["_GET"] => array(5) {
    ["add-ons/th-install-upgrade"] => string(0) ""
    ["_xfRequestUri"] => string(29) "/community/admin.php?add-ons/"
    ["_xfWithData"] => string(1) "1"
    ["_xfToken"] => string(43) "1549555710,672df1439f82b3c90602c46bd5c9c314"
    ["_xfResponseType"] => string(4) "json"
  }
  ["_POST"] => array(0) {
  }
}

**Comment by LukasWieditz** [comment]
Closed with #3
