### ISSUE TITLE
No obvious way to download Install & Upgrade

### ISSUE THREAD

**Issue by chrissnell-okta** [Audentio/xf2-installupgrade#38]
The UI-X 2 instruction say that I&U is now the recommended way to update the UI-X add-on.  The [I&U docs](https://help.themehouse.com/en/articles/3443453-installing-install-upgrade) reference the customer area as the place to download it but I don't see it anywhere.  Can you update the docs with a link please?

**Comment by LukasWieditz** [comment]
It's available from the [product page on the ThemeHouse website](https://www.themehouse.com/xenforo/2/addons/install-and-upgrade).
