### ISSUE TITLE
Can't install on XF 2.1

### ISSUE THREAD

**Issue by teamracing** [Audentio/xf2-installupgrade#9]
Fresh XF 2.1 install, attempting to install UIX Pro.

After running install & upgrade installation I don't see any sign of the addon in ACP. 

PHP 7.3.1, Maria DB 10.3.

Following is the error in the backend:

Exception: Could not get runner for job ThemeHouse\InstallAndUpgrade:PostInstall (unique: ). Skipping. src/XF/Job/Manager.php:239
Generated by: Unknown account Feb 6, 2019 at 5:43 PM
Stack trace
#0 src/XF/Job/Manager.php(195): XF\Job\Manager->runJobInternal(Array, G)
#1 src/XF/Job/Manager.php(79): XF\Job\Manager->runJobEntry(Array, G)
#2 job.php(42): XF\Job\Manager->runQueue(false, 8)
#3 {main}
Request state
array(4) {
  ["url"] => string(18) "/community/job.php"
  ["referrer"] => string(50) "https://mysite.com/community/admin.php?add-ons/"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}

**Comment by LukasWieditz** [comment]
The error is safe to ignore.

The add-on itself integrates in what is already there. See our [documentation](https://www.themehouse.com/help/documentation/installupgrade) on how to use it.

**Comment by ichpen** [comment]
> The error is safe to ignore.
> 
> The add-on itself integrates in what is already there. See our [documentation](https://www.themehouse.com/help/documentation/installupgrade) on how to use it.

Thanks.

Just created another issue, different error #10

**Comment by ichpen** [comment]
You should consider revising UIX pro docs or referencing Install&Upgrade docs.
